server:
  port: 8080



spring:
  servlet:
    multipart:
      max-file-size: '100MB'
      max-request-size: '100MB'

  jpa:
    hibernate:
      ddl-auto: 'none'
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: 'org.hibernate.dialect.MySQL8Dialect'
    show-sql: true
  datasource:
    username: 'root'
    password: 'root'
    url: 'jdbc:mysql://localhost:3306/prova'